/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author dell
 */
public class Comment extends javax.swing.JDialog {

    /**
     * Creates new form Comment
     */
    public Comment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneladdcomment = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textcomment = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        panellogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelcomment = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(537, 415));

        paneladdcomment.setPreferredSize(new java.awt.Dimension(537, 101));
        paneladdcomment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textcomment.setColumns(20);
        textcomment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textcomment.setForeground(new java.awt.Color(153, 153, 153));
        textcomment.setLineWrap(true);
        textcomment.setRows(5);
        textcomment.setText("\n  Add your comment");
        textcomment.setWrapStyleWord(true);
        textcomment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        jScrollPane2.setViewportView(textcomment);

        paneladdcomment.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 350, 60));

        jLabel2.setBackground(new java.awt.Color(55, 115, 228));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Submit");
        jLabel2.setOpaque(true);
        paneladdcomment.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 120, 60));

        getContentPane().add(paneladdcomment, java.awt.BorderLayout.PAGE_END);

        panellogo.setBackground(new java.awt.Color(233, 242, 245));
        panellogo.setPreferredSize(new java.awt.Dimension(537, 101));
        panellogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        panellogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 10, 140, 80));

        getContentPane().add(panellogo, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 101));

        panelcomment.setPreferredSize(new java.awt.Dimension(535, 211));
        panelcomment.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 17, 20));
        jScrollPane1.setViewportView(panelcomment);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Comment dialog = new Comment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel paneladdcomment;
    private javax.swing.JPanel panelcomment;
    private javax.swing.JPanel panellogo;
    private javax.swing.JTextArea textcomment;
    // End of variables declaration//GEN-END:variables
}
