/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author dell
 */
public class Creatpod extends javax.swing.JDialog {

    /**
     * Creates new form Creatpod
     */
    public Creatpod(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panellogo = new javax.swing.JPanel();
        labellogoo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labeltitle = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textdexription = new javax.swing.JTextArea();
        labeladdimage = new javax.swing.JLabel();
        labelimagepath = new javax.swing.JLabel();
        labelcreate = new javax.swing.JLabel();
        erroraddimage = new javax.swing.JLabel();
        errortitle1 = new javax.swing.JLabel();
        errordescription1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panellogo.setBackground(new java.awt.Color(233, 242, 245));
        panellogo.setPreferredSize(new java.awt.Dimension(800, 121));
        panellogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panellogo.add(labellogoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 6, 200, 100));

        getContentPane().add(panellogo, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 581));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeltitle.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        labeltitle.setForeground(new java.awt.Color(153, 153, 153));
        labeltitle.setText("Podcast title");
        labeltitle.setBorder(null);
        jPanel1.add(labeltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 420, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 420, -1));

        textdexription.setColumns(20);
        textdexription.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textdexription.setForeground(new java.awt.Color(153, 153, 153));
        textdexription.setRows(5);
        textdexription.setText("  Podcast description");
        jScrollPane1.setViewportView(textdexription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 420, 140));

        labeladdimage.setBackground(new java.awt.Color(238, 238, 238));
        labeladdimage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labeladdimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeladdimage.setText("Add image");
        labeladdimage.setOpaque(true);
        jPanel1.add(labeladdimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 386, 150, 40));

        labelimagepath.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelimagepath.setForeground(new java.awt.Color(102, 102, 102));
        labelimagepath.setText("Image path");
        jPanel1.add(labelimagepath, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 386, 390, 40));

        labelcreate.setBackground(new java.awt.Color(55, 115, 228));
        labelcreate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelcreate.setForeground(new java.awt.Color(255, 255, 255));
        labelcreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcreate.setText("Create");
        labelcreate.setOpaque(true);
        jPanel1.add(labelcreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 260, 50));

        erroraddimage.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        erroraddimage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(erroraddimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 420, 20));

        errortitle1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        errortitle1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errortitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 420, 20));

        errordescription1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        errordescription1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errordescription1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 420, 20));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creatpod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creatpod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creatpod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creatpod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Creatpod dialog = new Creatpod(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel erroraddimage;
    private javax.swing.JLabel errordescription1;
    private javax.swing.JLabel errortitle1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labeladdimage;
    private javax.swing.JLabel labelcreate;
    private javax.swing.JLabel labelimagepath;
    private javax.swing.JLabel labellogoo;
    private javax.swing.JTextField labeltitle;
    private javax.swing.JPanel panellogo;
    private javax.swing.JTextArea textdexription;
    // End of variables declaration//GEN-END:variables
}
