/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dell
 */
public class essy extends javax.swing.JFrame {

    /**
     * Creates new form essy
     */
    public essy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menubar = new javax.swing.JPanel();
        logopanel = new javax.swing.JPanel();
        labellogo = new javax.swing.JLabel();
        panelreglog = new javax.swing.JPanel();
        labelreg = new javax.swing.JLabel();
        labellogin = new javax.swing.JLabel();
        panelrechcreatupload = new javax.swing.JPanel();
        panelrech = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textrech = new javax.swing.JTextField();
        labelrech = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelcreatupload = new javax.swing.JPanel();
        labelcreatpod = new javax.swing.JLabel();
        labelupload = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        labelexplore = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        labelmypod = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        labelsubscription = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelpodexpl = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        panelpoddef = new javax.swing.JPanel();
        panelpoddefnorth = new javax.swing.JPanel();
        panelpoddefinition = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        labelimgpod = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        panelsubscription = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        paneltitleaut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        paneldescription = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelpoddefsouht = new javax.swing.JPanel();
        panelepisode = new javax.swing.JPanel();
        panelnbepisode = new javax.swing.JPanel();
        labelnbepisode = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelaudiopath = new javax.swing.JLabel();
        panellikelengthcomment = new javax.swing.JPanel();
        labellike = new javax.swing.JLabel();
        labelcomment = new javax.swing.JLabel();
        labellenght = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        paneltitledescription = new javax.swing.JPanel();
        labeltitleepisode = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textepisode = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        labeltitleepo = new javax.swing.JLabel();
        labeltitlepod = new javax.swing.JLabel();
        labelname = new javax.swing.JLabel();
        labelplaypause = new javax.swing.JLabel();
        labeldis = new javax.swing.JLabel();
        labeladvanse = new javax.swing.JLabel();
        labeltime = new javax.swing.JLabel();
        progressbar = new javax.swing.JSlider();
        labeldurattion = new javax.swing.JLabel();
        prog = new javax.swing.JProgressBar();
        labelimg = new javax.swing.JLabel();
        labelcloseepisode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menubar.setBackground(new java.awt.Color(233, 242, 245));
        menubar.setPreferredSize(new java.awt.Dimension(982, 101));
        menubar.setLayout(new java.awt.BorderLayout());

        logopanel.setBackground(new java.awt.Color(233, 242, 245));
        logopanel.setPreferredSize(new java.awt.Dimension(147, 102));
        logopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labellogo.setPreferredSize(new java.awt.Dimension(80, 80));
        logopanel.add(labellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 80));

        menubar.add(logopanel, java.awt.BorderLayout.LINE_START);

        panelreglog.setBackground(new java.awt.Color(233, 242, 245));
        panelreglog.setPreferredSize(new java.awt.Dimension(177, 102));
        panelreglog.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 18));

        labelreg.setBackground(new java.awt.Color(255, 255, 255));
        labelreg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelreg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelreg.setText("Register");
        labelreg.setOpaque(true);
        labelreg.setPreferredSize(new java.awt.Dimension(68, 22));
        panelreglog.add(labelreg);

        labellogin.setBackground(new java.awt.Color(55, 115, 228));
        labellogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labellogin.setForeground(new java.awt.Color(255, 255, 255));
        labellogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labellogin.setText("Log in");
        labellogin.setOpaque(true);
        labellogin.setPreferredSize(new java.awt.Dimension(68, 22));
        panelreglog.add(labellogin);

        menubar.add(panelreglog, java.awt.BorderLayout.LINE_END);

        panelrechcreatupload.setBackground(new java.awt.Color(233, 242, 245));
        panelrechcreatupload.setPreferredSize(new java.awt.Dimension(658, 102));
        panelrechcreatupload.setLayout(new java.awt.GridLayout(2, 1));

        panelrech.setBackground(new java.awt.Color(233, 242, 245));
        panelrech.setPreferredSize(new java.awt.Dimension(664, 51));
        panelrech.setLayout(new javax.swing.BoxLayout(panelrech, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setText("             ");
        panelrech.add(jLabel8);

        jLabel9.setText("          ");
        panelrech.add(jLabel9);

        jLabel10.setText("           ");
        panelrech.add(jLabel10);

        textrech.setText("jTextField2");
        textrech.setPreferredSize(new java.awt.Dimension(100, 22));
        panelrech.add(textrech);

        labelrech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        labelrech.setPreferredSize(new java.awt.Dimension(37, 20));
        panelrech.add(labelrech);

        jLabel6.setText("             ");
        panelrech.add(jLabel6);

        jLabel7.setText("       ");
        panelrech.add(jLabel7);

        panelrechcreatupload.add(panelrech);

        panelcreatupload.setBackground(new java.awt.Color(233, 242, 245));
        panelcreatupload.setPreferredSize(new java.awt.Dimension(664, 51));
        panelcreatupload.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 17, 17));

        labelcreatpod.setBackground(new java.awt.Color(55, 115, 228));
        labelcreatpod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelcreatpod.setForeground(new java.awt.Color(255, 255, 255));
        labelcreatpod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        labelcreatpod.setText("Creat a new podcast channel");
        labelcreatpod.setOpaque(true);
        labelcreatpod.setPreferredSize(new java.awt.Dimension(225, 30));
        panelcreatupload.add(labelcreatpod);

        labelupload.setBackground(new java.awt.Color(255, 255, 255));
        labelupload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Upload.png"))); // NOI18N
        labelupload.setText("Upload a new episode");
        labelupload.setOpaque(true);
        labelupload.setPreferredSize(new java.awt.Dimension(200, 30));
        panelcreatupload.add(labelupload);

        panelrechcreatupload.add(panelcreatupload);

        menubar.add(panelrechcreatupload, java.awt.BorderLayout.CENTER);

        getContentPane().add(menubar, java.awt.BorderLayout.PAGE_START);

        sidebar.setBackground(new java.awt.Color(233, 242, 245));
        sidebar.setPreferredSize(new java.awt.Dimension(149, 540));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelexplore.setBackground(new java.awt.Color(233, 242, 245));
        labelexplore.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelexplore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Compass.png"))); // NOI18N
        labelexplore.setText("  Explore");
        labelexplore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelexploreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelexploreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelexploreMouseExited(evt);
            }
        });
        sidebar.add(labelexplore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 130, 40));

        jPanel8.setBackground(new java.awt.Color(123, 184, 241));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        sidebar.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 10, 40));

        labelmypod.setBackground(new java.awt.Color(233, 242, 245));
        labelmypod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelmypod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Microphone.png"))); // NOI18N
        labelmypod.setText(" My podcast");
        labelmypod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelmypodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelmypodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelmypodMouseExited(evt);
            }
        });
        sidebar.add(labelmypod, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 140, 40));

        jPanel9.setBackground(new java.awt.Color(233, 242, 245));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        sidebar.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 10, 40));

        labelsubscription.setBackground(new java.awt.Color(233, 242, 245));
        labelsubscription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelsubscription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Thermometer.png"))); // NOI18N
        labelsubscription.setText("Subscription");
        labelsubscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelsubscriptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelsubscriptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelsubscriptionMouseExited(evt);
            }
        });
        sidebar.add(labelsubscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 130, 150, 40));

        jPanel10.setBackground(new java.awt.Color(233, 242, 245));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        sidebar.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 10, 40));

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(895, 537));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(895, 436));
        jPanel3.setLayout(new java.awt.CardLayout());

        jScrollPane3.setPreferredSize(new java.awt.Dimension(100, 101));

        panelpodexpl.setPreferredSize(new java.awt.Dimension(1000, 1000));
        panelpodexpl.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));
        jScrollPane3.setViewportView(panelpodexpl);

        jPanel3.add(jScrollPane3, "card2");

        jScrollPane4.setPreferredSize(new java.awt.Dimension(100, 101));

        panelpoddef.setPreferredSize(new java.awt.Dimension(1000, 1000));
        panelpoddef.setLayout(new java.awt.BorderLayout());

        panelpoddefnorth.setPreferredSize(new java.awt.Dimension(1000, 281));
        panelpoddefnorth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelpoddefinition.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(272, 261));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelimgpod.setText("jLabel1");
        jPanel6.add(labelimgpod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 230));

        panelpoddefinition.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setPreferredSize(new java.awt.Dimension(558, 261));
        jPanel7.setLayout(new java.awt.BorderLayout());

        panelsubscription.setBackground(new java.awt.Color(255, 255, 255));
        panelsubscription.setPreferredSize(new java.awt.Dimension(558, 49));
        panelsubscription.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trash.png"))); // NOI18N
        jLabel3.setText("          Delete");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red));
        jLabel3.setOpaque(true);
        panelsubscription.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 180, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(55, 115, 228));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit.png"))); // NOI18N
        jLabel11.setText("           Edit");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        jLabel11.setOpaque(true);
        panelsubscription.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        jPanel7.add(panelsubscription, java.awt.BorderLayout.PAGE_END);

        paneltitleaut.setBackground(new java.awt.Color(255, 255, 255));
        paneltitleaut.setPreferredSize(new java.awt.Dimension(558, 69));
        paneltitleaut.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        paneltitleaut.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 260, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        paneltitleaut.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 260, 40));

        jPanel7.add(paneltitleaut, java.awt.BorderLayout.PAGE_START);

        paneldescription.setPreferredSize(new java.awt.Dimension(558, 144));
        paneldescription.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextArea1);

        paneldescription.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 140));

        jPanel7.add(paneldescription, java.awt.BorderLayout.CENTER);

        panelpoddefinition.add(jPanel7, java.awt.BorderLayout.CENTER);

        panelpoddefnorth.add(panelpoddefinition, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 960, 260));

        panelpoddef.add(panelpoddefnorth, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 101));

        panelpoddefsouht.setPreferredSize(new java.awt.Dimension(1000, 1000));
        panelpoddefsouht.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 27, 20));

        panelepisode.setBackground(new java.awt.Color(255, 255, 255));
        panelepisode.setPreferredSize(new java.awt.Dimension(832, 101));
        panelepisode.setLayout(new java.awt.BorderLayout());

        panelnbepisode.setBackground(new java.awt.Color(255, 255, 255));
        panelnbepisode.setPreferredSize(new java.awt.Dimension(58, 102));
        panelnbepisode.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelnbepisode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelnbepisode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelnbepisode.setText("1");
        panelnbepisode.add(labelnbepisode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, 20));

        jLabel4.setText("1");
        panelnbepisode.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 10, 30, -1));

        jLabel5.setText("300");
        panelnbepisode.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 30, -1));
        panelnbepisode.add(labelaudiopath, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 10));

        panelepisode.add(panelnbepisode, java.awt.BorderLayout.LINE_START);

        panellikelengthcomment.setBackground(new java.awt.Color(255, 255, 255));
        panellikelengthcomment.setPreferredSize(new java.awt.Dimension(153, 102));
        panellikelengthcomment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labellike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/like.png"))); // NOI18N
        labellike.setText("  Like");
        panellikelengthcomment.add(labellike, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        labelcomment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comments.png"))); // NOI18N
        panellikelengthcomment.add(labelcomment, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 40, 30));

        labellenght.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labellenght.setText("jLabel13");
        panellikelengthcomment.add(labellenght, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edit.png"))); // NOI18N
        panellikelengthcomment.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 30, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trash.png"))); // NOI18N
        panellikelengthcomment.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 30, 30));

        panelepisode.add(panellikelengthcomment, java.awt.BorderLayout.LINE_END);

        paneltitledescription.setBackground(new java.awt.Color(255, 255, 255));
        paneltitledescription.setPreferredSize(new java.awt.Dimension(674, 103));
        paneltitledescription.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeltitleepisode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labeltitleepisode.setText("jLabel5");
        paneltitledescription.add(labeltitleepisode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 20));

        textepisode.setColumns(20);
        textepisode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textepisode.setForeground(new java.awt.Color(51, 51, 51));
        textepisode.setRows(5);
        jScrollPane5.setViewportView(textepisode);

        paneltitledescription.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 30, 610, 60));

        panelepisode.add(paneltitledescription, java.awt.BorderLayout.CENTER);

        panelpoddefsouht.add(panelepisode);

        jScrollPane1.setViewportView(panelpoddefsouht);

        panelpoddef.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jScrollPane4.setViewportView(panelpoddef);

        jPanel3.add(jScrollPane4, "card3");

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 145));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeltitleepo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labeltitleepo.setText("jLabel14");
        jPanel2.add(labeltitleepo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 360, 30));

        labeltitlepod.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        labeltitlepod.setText("jLabel15");
        jPanel2.add(labeltitlepod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 290, 30));

        labelname.setForeground(new java.awt.Color(51, 51, 51));
        labelname.setText("jLabel16");
        jPanel2.add(labelname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 210, -1));

        labelplaypause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pause.png"))); // NOI18N
        jPanel2.add(labelplaypause, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, 50));

        labeldis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alternate Undo.png"))); // NOI18N
        jPanel2.add(labeldis, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, 50));

        labeladvanse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alternate Redo2.png"))); // NOI18N
        jPanel2.add(labeladvanse, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, 50));

        labeltime.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        labeltime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(labeltime, new org.netbeans.lib.awtextra.AbsoluteConstraints(913, 40, 90, 40));

        progressbar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(progressbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        labeldurattion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel2.add(labeldurattion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 90, 40));

        prog.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(prog, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1080, 10));
        jPanel2.add(labelimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, 90, 110));

        labelcloseepisode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelcloseepisode.setForeground(new java.awt.Color(55, 115, 228));
        labelcloseepisode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelcloseepisode.setText("Close episode");
        labelcloseepisode.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        jPanel2.add(labelcloseepisode, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 150, 40));

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelexploreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexploreMouseClicked
        // TODO add your handling code here:
        labelexplore.setBackground(Color.decode("#7BB8F1"));
        labelexplore.setBackground(Color.decode("#E9F2F5"));
        panelpoddef.setVisible(false);
        jScrollPane4.setVisible(false);
        jScrollPane3.setVisible(true);
        panelpodexpl.setVisible(true);
    }//GEN-LAST:event_labelexploreMouseClicked

    private void labelexploreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexploreMouseEntered
        // TODO add your handling code here:
        labelexplore.setCursor(new Cursor(Cursor.HAND_CURSOR));
        labelexplore.setBackground(Color.decode("#BEFFFF"));
        labelexplore.setOpaque(true);
    }//GEN-LAST:event_labelexploreMouseEntered

    private void labelexploreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelexploreMouseExited
        // TODO add your handling code here:
        labelexplore.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        labelexplore.setBackground(Color.decode("#E9F2F5"));
        labelexplore.setOpaque(true);
    }//GEN-LAST:event_labelexploreMouseExited

    private void labelmypodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmypodMouseClicked
        // TODO add your handling code here:
        /*panelrech.setBackground(Color.decode("#7BB8F1"));
        panelcreatupload.setBackground(Color.decode("#E9F2F5"));
        panelPodcats.setVisible(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(true);
        panelComments.setVisible(true);*/
    }//GEN-LAST:event_labelmypodMouseClicked

    private void labelmypodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmypodMouseEntered
        // TODO add your handling code here:
        /* labelmypod.setCursor(new Cursor(Cursor.HAND_CURSOR));
        labelmypod.setBackground(Color.decode("#BEFFFF"));
        labelmypod.setOpaque(true);*/
    }//GEN-LAST:event_labelmypodMouseEntered

    private void labelmypodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelmypodMouseExited
        // TODO add your handling code here:
        /*labelmypod.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        labelmypod.setBackground(Color.decode("#E9F2F5"));
        labelmypod.setOpaque(true);*/
    }//GEN-LAST:event_labelmypodMouseExited

    private void labelsubscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsubscriptionMouseClicked
        // TODO add your handling code here:
        JPanel kkk=new JPanel();

        kkk.setPreferredSize(new Dimension(895, 101));
        //panelpodexpl.setPreferredSize(new Dimension(panelpodexpl.getWidth(),panelpodexpl.getHeight()-105));
        kkk.setBackground(Color.white);
        jPanel1.setVisible(false);
        jPanel1.add(kkk,BorderLayout.SOUTH);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_labelsubscriptionMouseClicked

    private void labelsubscriptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsubscriptionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_labelsubscriptionMouseEntered

    private void labelsubscriptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsubscriptionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelsubscriptionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(essy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(essy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(essy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(essy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new essy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labeladvanse;
    private javax.swing.JLabel labelaudiopath;
    private javax.swing.JLabel labelcloseepisode;
    private javax.swing.JLabel labelcomment;
    private javax.swing.JLabel labelcreatpod;
    private javax.swing.JLabel labeldis;
    private javax.swing.JLabel labeldurattion;
    private javax.swing.JLabel labelexplore;
    private javax.swing.JLabel labelimg;
    private javax.swing.JLabel labelimgpod;
    private javax.swing.JLabel labellenght;
    private javax.swing.JLabel labellike;
    private javax.swing.JLabel labellogin;
    private javax.swing.JLabel labellogo;
    private javax.swing.JLabel labelmypod;
    private javax.swing.JLabel labelname;
    private javax.swing.JLabel labelnbepisode;
    private javax.swing.JLabel labelplaypause;
    private javax.swing.JLabel labelrech;
    private javax.swing.JLabel labelreg;
    private javax.swing.JLabel labelsubscription;
    private javax.swing.JLabel labeltime;
    private javax.swing.JLabel labeltitleepisode;
    private javax.swing.JLabel labeltitleepo;
    private javax.swing.JLabel labeltitlepod;
    private javax.swing.JLabel labelupload;
    private javax.swing.JPanel logopanel;
    private javax.swing.JPanel menubar;
    private javax.swing.JPanel panelcreatupload;
    private javax.swing.JPanel paneldescription;
    private javax.swing.JPanel panelepisode;
    private javax.swing.JPanel panellikelengthcomment;
    private javax.swing.JPanel panelnbepisode;
    private javax.swing.JPanel panelpoddef;
    private javax.swing.JPanel panelpoddefinition;
    private javax.swing.JPanel panelpoddefnorth;
    private javax.swing.JPanel panelpoddefsouht;
    private javax.swing.JPanel panelpodexpl;
    private javax.swing.JPanel panelrech;
    private javax.swing.JPanel panelrechcreatupload;
    private javax.swing.JPanel panelreglog;
    private javax.swing.JPanel panelsubscription;
    private javax.swing.JPanel paneltitleaut;
    private javax.swing.JPanel paneltitledescription;
    private javax.swing.JProgressBar prog;
    private javax.swing.JSlider progressbar;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTextArea textepisode;
    private javax.swing.JTextField textrech;
    // End of variables declaration//GEN-END:variables
}
