/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author dell
 */
public class Register extends javax.swing.JDialog {

    /**
     * Creates new form Register
     */
    public Register(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panellogooo = new javax.swing.JPanel();
        labellogooo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        firstname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        email = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        occupation = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lastname = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        dateofbirth = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        men = new javax.swing.JRadioButton();
        women = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();
        errordate = new javax.swing.JLabel();
        errorpassword = new javax.swing.JLabel();
        errorfirstname = new javax.swing.JLabel();
        errorlastname1 = new javax.swing.JLabel();
        erroroccup = new javax.swing.JLabel();
        errorsexe = new javax.swing.JLabel();
        erroremail5 = new javax.swing.JLabel();
        erroremail6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panellogooo.setBackground(new java.awt.Color(233, 242, 245));
        panellogooo.setPreferredSize(new java.awt.Dimension(800, 126));
        panellogooo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panellogooo.add(labellogooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 180, 100));

        getContentPane().add(panellogooo, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 576));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(153, 153, 153));
        firstname.setText("First name");
        firstname.setBorder(null);
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 270, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 270, 20));

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(153, 153, 153));
        email.setText("Email");
        email.setBorder(null);
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 270, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 270, 20));

        occupation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        occupation.setForeground(new java.awt.Color(153, 153, 153));
        occupation.setText("Occupation");
        occupation.setBorder(null);
        jPanel2.add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 270, 40));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 270, 20));

        lastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(153, 153, 153));
        lastname.setText("Last name");
        lastname.setBorder(null);
        jPanel2.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 270, 40));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 270, 20));

        dateofbirth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateofbirth.setForeground(new java.awt.Color(153, 153, 153));
        dateofbirth.setText("Date of birth dd/mm/yyyy");
        dateofbirth.setBorder(null);
        jPanel2.add(dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 270, 40));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 270, 20));

        password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setText("Password");
        password.setBorder(null);
        password.setEchoChar('*');
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 312, 270, 40));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 270, 20));

        buttonGroup1.add(men);
        men.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        men.setText("Men");
        jPanel2.add(men, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        buttonGroup1.add(women);
        women.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        women.setText("Women");
        jPanel2.add(women, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Sexe    :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 60, 40));

        signup.setBackground(new java.awt.Color(55, 115, 228));
        signup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editw.png"))); // NOI18N
        signup.setText("Sign up");
        signup.setOpaque(true);
        jPanel2.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 180, 40));

        errordate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errordate.setForeground(new java.awt.Color(255, 0, 0));
        errordate.setText("jLabel2");
        jPanel2.add(errordate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 340, 40));

        errorpassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errorpassword.setForeground(new java.awt.Color(102, 102, 102));
        errorpassword.setText("your password must not exeed 8 caractere");
        jPanel2.add(errorpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 370, 40));

        errorfirstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errorfirstname.setForeground(new java.awt.Color(255, 0, 0));
        errorfirstname.setText("jLabel2");
        jPanel2.add(errorfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 340, 40));

        errorlastname1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errorlastname1.setForeground(new java.awt.Color(255, 0, 0));
        errorlastname1.setText("jLabel2");
        jPanel2.add(errorlastname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 370, 40));

        erroroccup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        erroroccup.setForeground(new java.awt.Color(255, 0, 0));
        erroroccup.setText("jLabel2");
        jPanel2.add(erroroccup, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 340, 40));

        errorsexe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errorsexe.setForeground(new java.awt.Color(255, 0, 0));
        errorsexe.setText("jLabel2");
        errorsexe.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(errorsexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 400, 40));

        erroremail5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        erroremail5.setForeground(new java.awt.Color(255, 0, 0));
        erroremail5.setText("jLabel2");
        jPanel2.add(erroremail5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 370, 40));

        erroremail6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        erroremail6.setForeground(new java.awt.Color(255, 0, 0));
        erroremail6.setText("jLabel2");
        jPanel2.add(erroremail6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 270, 40));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Register dialog = new Register(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dateofbirth;
    private javax.swing.JTextField email;
    private javax.swing.JLabel errordate;
    private javax.swing.JLabel erroremail5;
    private javax.swing.JLabel erroremail6;
    private javax.swing.JLabel errorfirstname;
    private javax.swing.JLabel errorlastname1;
    private javax.swing.JLabel erroroccup;
    private javax.swing.JLabel errorpassword;
    private javax.swing.JLabel errorsexe;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labellogooo;
    private javax.swing.JTextField lastname;
    private javax.swing.JRadioButton men;
    private javax.swing.JTextField occupation;
    private javax.swing.JPanel panellogooo;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel signup;
    private javax.swing.JRadioButton women;
    // End of variables declaration//GEN-END:variables
}
