/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author dell
 */
public class Upload extends javax.swing.JDialog {

    /**
     * Creates new form Upload
     */
    public Upload(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panellogo = new javax.swing.JPanel();
        labellogoo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        episodetitle = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        erroraddepisode = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textepisodedescription = new javax.swing.JTextArea();
        errorepisodetitle = new javax.swing.JLabel();
        labeladdaudio = new javax.swing.JLabel();
        podcastchose = new javax.swing.JComboBox<>();
        errordescription = new javax.swing.JLabel();
        labelpodcastch = new javax.swing.JLabel();
        labelepisodepath = new javax.swing.JLabel();
        errorpodcastchose = new javax.swing.JLabel();
        labelupload = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panellogo.setBackground(new java.awt.Color(233, 242, 245));
        panellogo.setPreferredSize(new java.awt.Dimension(800, 101));
        panellogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panellogo.add(labellogoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 170, 80));

        getContentPane().add(panellogo, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 601));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        episodetitle.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        episodetitle.setForeground(new java.awt.Color(153, 153, 153));
        episodetitle.setText("Episode title");
        episodetitle.setBorder(null);
        jPanel1.add(episodetitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 420, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 420, 10));

        erroraddepisode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        erroraddepisode.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(erroraddepisode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 430, 30));

        textepisodedescription.setColumns(20);
        textepisodedescription.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        textepisodedescription.setForeground(new java.awt.Color(153, 153, 153));
        textepisodedescription.setRows(5);
        textepisodedescription.setText(" Episode description");
        jScrollPane1.setViewportView(textepisodedescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 420, 120));

        errorepisodetitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        errorepisodetitle.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorepisodetitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 420, 30));

        labeladdaudio.setBackground(new java.awt.Color(238, 238, 238));
        labeladdaudio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labeladdaudio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeladdaudio.setText("Add episode audio");
        labeladdaudio.setOpaque(true);
        jPanel1.add(labeladdaudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 160, 40));

        podcastchose.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        podcastchose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(podcastchose, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 240, 30));

        errordescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        errordescription.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errordescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 420, 30));

        labelpodcastch.setBackground(new java.awt.Color(238, 238, 238));
        labelpodcastch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelpodcastch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelpodcastch.setText("Podcast channel");
        labelpodcastch.setOpaque(true);
        jPanel1.add(labelpodcastch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 326, 150, 40));

        labelepisodepath.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        labelepisodepath.setForeground(new java.awt.Color(102, 102, 102));
        labelepisodepath.setText("Episode audio path");
        jPanel1.add(labelepisodepath, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 436, 250, 30));

        errorpodcastchose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        errorpodcastchose.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorpodcastchose, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 430, 30));

        labelupload.setBackground(new java.awt.Color(55, 115, 228));
        labelupload.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelupload.setForeground(new java.awt.Color(255, 255, 255));
        labelupload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelupload.setText("Upload");
        labelupload.setOpaque(true);
        jPanel1.add(labelupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 150, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Upload dialog = new Upload(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField episodetitle;
    private javax.swing.JLabel erroraddepisode;
    private javax.swing.JLabel errordescription;
    private javax.swing.JLabel errorepisodetitle;
    private javax.swing.JLabel errorpodcastchose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labeladdaudio;
    private javax.swing.JLabel labelepisodepath;
    private javax.swing.JLabel labellogoo;
    private javax.swing.JLabel labelpodcastch;
    private javax.swing.JLabel labelupload;
    private javax.swing.JPanel panellogo;
    private javax.swing.JComboBox<String> podcastchose;
    private javax.swing.JTextArea textepisodedescription;
    // End of variables declaration//GEN-END:variables
}
